// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
part 'geocoding_dto.freezed.dart';
part 'geocoding_dto.g.dart';

@freezed
class GeocodingDto with _$GeocodingDto {
  const factory GeocodingDto({
    @JsonKey(name: 'name') String? name,
    @JsonKey(name: 'local_names') LocalNames? localNames,
    @JsonKey(name: 'lat') double? lat,
    @JsonKey(name: 'lon') double? lon,
    @JsonKey(name: 'country') String? country,
    @JsonKey(name: 'state') String? state,
  }) = _GeocodingDto;

  factory GeocodingDto.fromJson(Map<String, Object?> json) =>
      _$GeocodingDtoFromJson(json);
}

@freezed
class LocalNames with _$LocalNames {
  const factory LocalNames({
    @JsonKey(name: 'ms') String? ms,
    @JsonKey(name: 'gu') String? gu,
    @JsonKey(name: 'is') String? isProperty,
    @JsonKey(name: 'wa') String? wa,
    @JsonKey(name: 'mg') String? mg,
    @JsonKey(name: 'gl') String? gl,
    @JsonKey(name: 'om') String? om,
    @JsonKey(name: 'ku') String? ku,
    @JsonKey(name: 'tw') String? tw,
    @JsonKey(name: 'mk') String? mk,
    @JsonKey(name: 'ee') String? ee,
    @JsonKey(name: 'fj') String? fj,
    @JsonKey(name: 'gd') String? gd,
    @JsonKey(name: 'ky') String? ky,
    @JsonKey(name: 'yo') String? yo,
    @JsonKey(name: 'zu') String? zu,
    @JsonKey(name: 'bg') String? bg,
    @JsonKey(name: 'tk') String? tk,
    @JsonKey(name: 'co') String? co,
    @JsonKey(name: 'sh') String? sh,
    @JsonKey(name: 'de') String? de,
    @JsonKey(name: 'kl') String? kl,
    @JsonKey(name: 'bi') String? bi,
    @JsonKey(name: 'km') String? km,
    @JsonKey(name: 'lt') String? lt,
    @JsonKey(name: 'fi') String? fi,
    @JsonKey(name: 'fy') String? fy,
    @JsonKey(name: 'ba') String? ba,
    @JsonKey(name: 'sc') String? sc,
    @JsonKey(name: 'feature_name') String? featureName,
    @JsonKey(name: 'ja') String? ja,
    @JsonKey(name: 'am') String? am,
    @JsonKey(name: 'sk') String? sk,
    @JsonKey(name: 'mr') String? mr,
    @JsonKey(name: 'es') String? es,
    @JsonKey(name: 'sq') String? sq,
    @JsonKey(name: 'te') String? te,
    @JsonKey(name: 'br') String? br,
    @JsonKey(name: 'uz') String? uz,
    @JsonKey(name: 'da') String? da,
    @JsonKey(name: 'sw') String? sw,
    @JsonKey(name: 'fa') String? fa,
    @JsonKey(name: 'sr') String? sr,
    @JsonKey(name: 'cu') String? cu,
    @JsonKey(name: 'ln') String? ln,
    @JsonKey(name: 'na') String? na,
    @JsonKey(name: 'wo') String? wo,
    @JsonKey(name: 'ig') String? ig,
    @JsonKey(name: 'to') String? to,
    @JsonKey(name: 'ta') String? ta,
    @JsonKey(name: 'mt') String? mt,
    @JsonKey(name: 'ar') String? ar,
    @JsonKey(name: 'su') String? su,
    @JsonKey(name: 'ab') String? ab,
    @JsonKey(name: 'ps') String? ps,
    @JsonKey(name: 'bm') String? bm,
    @JsonKey(name: 'mi') String? mi,
    @JsonKey(name: 'kn') String? kn,
    @JsonKey(name: 'kv') String? kv,
    @JsonKey(name: 'os') String? os,
    @JsonKey(name: 'bn') String? bn,
    @JsonKey(name: 'li') String? li,
    @JsonKey(name: 'vi') String? vi,
    @JsonKey(name: 'zh') String? zh,
    @JsonKey(name: 'eo') String? eo,
    @JsonKey(name: 'ha') String? ha,
    @JsonKey(name: 'tt') String? tt,
    @JsonKey(name: 'lb') String? lb,
    @JsonKey(name: 'ce') String? ce,
    @JsonKey(name: 'hu') String? hu,
    @JsonKey(name: 'it') String? it,
    @JsonKey(name: 'tl') String? tl,
    @JsonKey(name: 'pl') String? pl,
    @JsonKey(name: 'sm') String? sm,
    @JsonKey(name: 'en') String? en,
    @JsonKey(name: 'vo') String? vo,
    @JsonKey(name: 'el') String? el,
    @JsonKey(name: 'sn') String? sn,
    @JsonKey(name: 'fr') String? fr,
    @JsonKey(name: 'cs') String? cs,
    @JsonKey(name: 'io') String? io,
    @JsonKey(name: 'hi') String? hi,
    @JsonKey(name: 'et') String? et,
    @JsonKey(name: 'pa') String? pa,
    @JsonKey(name: 'av') String? av,
    @JsonKey(name: 'ko') String? ko,
    @JsonKey(name: 'bh') String? bh,
    @JsonKey(name: 'yi') String? yi,
    @JsonKey(name: 'sa') String? sa,
    @JsonKey(name: 'sl') String? sl,
    @JsonKey(name: 'hr') String? hr,
    @JsonKey(name: 'si') String? si,
    @JsonKey(name: 'so') String? so,
    @JsonKey(name: 'gn') String? gn,
    @JsonKey(name: 'ay') String? ay,
    @JsonKey(name: 'se') String? se,
    @JsonKey(name: 'sd') String? sd,
    @JsonKey(name: 'af') String? af,
    @JsonKey(name: 'ga') String? ga,
    @JsonKey(name: 'or') String? or,
    @JsonKey(name: 'ia') String? ia,
    @JsonKey(name: 'ie') String? ie,
    @JsonKey(name: 'ug') String? ug,
    @JsonKey(name: 'nl') String? nl,
    @JsonKey(name: 'gv') String? gv,
    @JsonKey(name: 'qu') String? qu,
    @JsonKey(name: 'be') String? be,
    @JsonKey(name: 'an') String? an,
    @JsonKey(name: 'fo') String? fo,
    @JsonKey(name: 'hy') String? hy,
    @JsonKey(name: 'nv') String? nv,
    @JsonKey(name: 'bo') String? bo,
    @JsonKey(name: 'ascii') String? ascii,
    @JsonKey(name: 'id') String? id,
    @JsonKey(name: 'lv') String? lv,
    @JsonKey(name: 'ca') String? ca,
    @JsonKey(name: 'no') String? no,
    @JsonKey(name: 'nn') String? nn,
    @JsonKey(name: 'ml') String? ml,
    @JsonKey(name: 'my') String? my,
    @JsonKey(name: 'ne') String? ne,
    @JsonKey(name: 'he') String? he,
    @JsonKey(name: 'cy') String? cy,
    @JsonKey(name: 'lo') String? lo,
    @JsonKey(name: 'jv') String? jv,
    @JsonKey(name: 'sv') String? sv,
    @JsonKey(name: 'mn') String? mn,
    @JsonKey(name: 'tg') String? tg,
    @JsonKey(name: 'kw') String? kw,
    @JsonKey(name: 'cv') String? cv,
    @JsonKey(name: 'az') String? az,
    @JsonKey(name: 'oc') String? oc,
    @JsonKey(name: 'th') String? th,
    @JsonKey(name: 'ru') String? ru,
    @JsonKey(name: 'ny') String? ny,
    @JsonKey(name: 'bs') String? bs,
    @JsonKey(name: 'st') String? st,
    @JsonKey(name: 'ro') String? ro,
    @JsonKey(name: 'rm') String? rm,
    @JsonKey(name: 'ff') String? ff,
    @JsonKey(name: 'kk') String? kk,
    @JsonKey(name: 'uk') String? uk,
    @JsonKey(name: 'pt') String? pt,
    @JsonKey(name: 'tr') String? tr,
    @JsonKey(name: 'eu') String? eu,
    @JsonKey(name: 'ht') String? ht,
    @JsonKey(name: 'ka') String? ka,
    @JsonKey(name: 'ur') String? ur,
  }) = _LocalNames;

  factory LocalNames.fromJson(Map<String, Object?> json) =>
      _$LocalNamesFromJson(json);
}
