// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'geocoding_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$GeocodingDtoImpl _$$GeocodingDtoImplFromJson(Map<String, dynamic> json) =>
    _$GeocodingDtoImpl(
      name: json['name'] as String?,
      localNames: json['local_names'] == null
          ? null
          : LocalNames.fromJson(json['local_names'] as Map<String, dynamic>),
      lat: (json['lat'] as num?)?.toDouble(),
      lon: (json['lon'] as num?)?.toDouble(),
      country: json['country'] as String?,
      state: json['state'] as String?,
    );

Map<String, dynamic> _$$GeocodingDtoImplToJson(_$GeocodingDtoImpl instance) =>
    <String, dynamic>{
      'name': instance.name,
      'local_names': instance.localNames,
      'lat': instance.lat,
      'lon': instance.lon,
      'country': instance.country,
      'state': instance.state,
    };

_$LocalNamesImpl _$$LocalNamesImplFromJson(Map<String, dynamic> json) =>
    _$LocalNamesImpl(
      ms: json['ms'] as String?,
      gu: json['gu'] as String?,
      isProperty: json['is'] as String?,
      wa: json['wa'] as String?,
      mg: json['mg'] as String?,
      gl: json['gl'] as String?,
      om: json['om'] as String?,
      ku: json['ku'] as String?,
      tw: json['tw'] as String?,
      mk: json['mk'] as String?,
      ee: json['ee'] as String?,
      fj: json['fj'] as String?,
      gd: json['gd'] as String?,
      ky: json['ky'] as String?,
      yo: json['yo'] as String?,
      zu: json['zu'] as String?,
      bg: json['bg'] as String?,
      tk: json['tk'] as String?,
      co: json['co'] as String?,
      sh: json['sh'] as String?,
      de: json['de'] as String?,
      kl: json['kl'] as String?,
      bi: json['bi'] as String?,
      km: json['km'] as String?,
      lt: json['lt'] as String?,
      fi: json['fi'] as String?,
      fy: json['fy'] as String?,
      ba: json['ba'] as String?,
      sc: json['sc'] as String?,
      featureName: json['feature_name'] as String?,
      ja: json['ja'] as String?,
      am: json['am'] as String?,
      sk: json['sk'] as String?,
      mr: json['mr'] as String?,
      es: json['es'] as String?,
      sq: json['sq'] as String?,
      te: json['te'] as String?,
      br: json['br'] as String?,
      uz: json['uz'] as String?,
      da: json['da'] as String?,
      sw: json['sw'] as String?,
      fa: json['fa'] as String?,
      sr: json['sr'] as String?,
      cu: json['cu'] as String?,
      ln: json['ln'] as String?,
      na: json['na'] as String?,
      wo: json['wo'] as String?,
      ig: json['ig'] as String?,
      to: json['to'] as String?,
      ta: json['ta'] as String?,
      mt: json['mt'] as String?,
      ar: json['ar'] as String?,
      su: json['su'] as String?,
      ab: json['ab'] as String?,
      ps: json['ps'] as String?,
      bm: json['bm'] as String?,
      mi: json['mi'] as String?,
      kn: json['kn'] as String?,
      kv: json['kv'] as String?,
      os: json['os'] as String?,
      bn: json['bn'] as String?,
      li: json['li'] as String?,
      vi: json['vi'] as String?,
      zh: json['zh'] as String?,
      eo: json['eo'] as String?,
      ha: json['ha'] as String?,
      tt: json['tt'] as String?,
      lb: json['lb'] as String?,
      ce: json['ce'] as String?,
      hu: json['hu'] as String?,
      it: json['it'] as String?,
      tl: json['tl'] as String?,
      pl: json['pl'] as String?,
      sm: json['sm'] as String?,
      en: json['en'] as String?,
      vo: json['vo'] as String?,
      el: json['el'] as String?,
      sn: json['sn'] as String?,
      fr: json['fr'] as String?,
      cs: json['cs'] as String?,
      io: json['io'] as String?,
      hi: json['hi'] as String?,
      et: json['et'] as String?,
      pa: json['pa'] as String?,
      av: json['av'] as String?,
      ko: json['ko'] as String?,
      bh: json['bh'] as String?,
      yi: json['yi'] as String?,
      sa: json['sa'] as String?,
      sl: json['sl'] as String?,
      hr: json['hr'] as String?,
      si: json['si'] as String?,
      so: json['so'] as String?,
      gn: json['gn'] as String?,
      ay: json['ay'] as String?,
      se: json['se'] as String?,
      sd: json['sd'] as String?,
      af: json['af'] as String?,
      ga: json['ga'] as String?,
      or: json['or'] as String?,
      ia: json['ia'] as String?,
      ie: json['ie'] as String?,
      ug: json['ug'] as String?,
      nl: json['nl'] as String?,
      gv: json['gv'] as String?,
      qu: json['qu'] as String?,
      be: json['be'] as String?,
      an: json['an'] as String?,
      fo: json['fo'] as String?,
      hy: json['hy'] as String?,
      nv: json['nv'] as String?,
      bo: json['bo'] as String?,
      ascii: json['ascii'] as String?,
      id: json['id'] as String?,
      lv: json['lv'] as String?,
      ca: json['ca'] as String?,
      no: json['no'] as String?,
      nn: json['nn'] as String?,
      ml: json['ml'] as String?,
      my: json['my'] as String?,
      ne: json['ne'] as String?,
      he: json['he'] as String?,
      cy: json['cy'] as String?,
      lo: json['lo'] as String?,
      jv: json['jv'] as String?,
      sv: json['sv'] as String?,
      mn: json['mn'] as String?,
      tg: json['tg'] as String?,
      kw: json['kw'] as String?,
      cv: json['cv'] as String?,
      az: json['az'] as String?,
      oc: json['oc'] as String?,
      th: json['th'] as String?,
      ru: json['ru'] as String?,
      ny: json['ny'] as String?,
      bs: json['bs'] as String?,
      st: json['st'] as String?,
      ro: json['ro'] as String?,
      rm: json['rm'] as String?,
      ff: json['ff'] as String?,
      kk: json['kk'] as String?,
      uk: json['uk'] as String?,
      pt: json['pt'] as String?,
      tr: json['tr'] as String?,
      eu: json['eu'] as String?,
      ht: json['ht'] as String?,
      ka: json['ka'] as String?,
      ur: json['ur'] as String?,
    );

Map<String, dynamic> _$$LocalNamesImplToJson(_$LocalNamesImpl instance) =>
    <String, dynamic>{
      'ms': instance.ms,
      'gu': instance.gu,
      'is': instance.isProperty,
      'wa': instance.wa,
      'mg': instance.mg,
      'gl': instance.gl,
      'om': instance.om,
      'ku': instance.ku,
      'tw': instance.tw,
      'mk': instance.mk,
      'ee': instance.ee,
      'fj': instance.fj,
      'gd': instance.gd,
      'ky': instance.ky,
      'yo': instance.yo,
      'zu': instance.zu,
      'bg': instance.bg,
      'tk': instance.tk,
      'co': instance.co,
      'sh': instance.sh,
      'de': instance.de,
      'kl': instance.kl,
      'bi': instance.bi,
      'km': instance.km,
      'lt': instance.lt,
      'fi': instance.fi,
      'fy': instance.fy,
      'ba': instance.ba,
      'sc': instance.sc,
      'feature_name': instance.featureName,
      'ja': instance.ja,
      'am': instance.am,
      'sk': instance.sk,
      'mr': instance.mr,
      'es': instance.es,
      'sq': instance.sq,
      'te': instance.te,
      'br': instance.br,
      'uz': instance.uz,
      'da': instance.da,
      'sw': instance.sw,
      'fa': instance.fa,
      'sr': instance.sr,
      'cu': instance.cu,
      'ln': instance.ln,
      'na': instance.na,
      'wo': instance.wo,
      'ig': instance.ig,
      'to': instance.to,
      'ta': instance.ta,
      'mt': instance.mt,
      'ar': instance.ar,
      'su': instance.su,
      'ab': instance.ab,
      'ps': instance.ps,
      'bm': instance.bm,
      'mi': instance.mi,
      'kn': instance.kn,
      'kv': instance.kv,
      'os': instance.os,
      'bn': instance.bn,
      'li': instance.li,
      'vi': instance.vi,
      'zh': instance.zh,
      'eo': instance.eo,
      'ha': instance.ha,
      'tt': instance.tt,
      'lb': instance.lb,
      'ce': instance.ce,
      'hu': instance.hu,
      'it': instance.it,
      'tl': instance.tl,
      'pl': instance.pl,
      'sm': instance.sm,
      'en': instance.en,
      'vo': instance.vo,
      'el': instance.el,
      'sn': instance.sn,
      'fr': instance.fr,
      'cs': instance.cs,
      'io': instance.io,
      'hi': instance.hi,
      'et': instance.et,
      'pa': instance.pa,
      'av': instance.av,
      'ko': instance.ko,
      'bh': instance.bh,
      'yi': instance.yi,
      'sa': instance.sa,
      'sl': instance.sl,
      'hr': instance.hr,
      'si': instance.si,
      'so': instance.so,
      'gn': instance.gn,
      'ay': instance.ay,
      'se': instance.se,
      'sd': instance.sd,
      'af': instance.af,
      'ga': instance.ga,
      'or': instance.or,
      'ia': instance.ia,
      'ie': instance.ie,
      'ug': instance.ug,
      'nl': instance.nl,
      'gv': instance.gv,
      'qu': instance.qu,
      'be': instance.be,
      'an': instance.an,
      'fo': instance.fo,
      'hy': instance.hy,
      'nv': instance.nv,
      'bo': instance.bo,
      'ascii': instance.ascii,
      'id': instance.id,
      'lv': instance.lv,
      'ca': instance.ca,
      'no': instance.no,
      'nn': instance.nn,
      'ml': instance.ml,
      'my': instance.my,
      'ne': instance.ne,
      'he': instance.he,
      'cy': instance.cy,
      'lo': instance.lo,
      'jv': instance.jv,
      'sv': instance.sv,
      'mn': instance.mn,
      'tg': instance.tg,
      'kw': instance.kw,
      'cv': instance.cv,
      'az': instance.az,
      'oc': instance.oc,
      'th': instance.th,
      'ru': instance.ru,
      'ny': instance.ny,
      'bs': instance.bs,
      'st': instance.st,
      'ro': instance.ro,
      'rm': instance.rm,
      'ff': instance.ff,
      'kk': instance.kk,
      'uk': instance.uk,
      'pt': instance.pt,
      'tr': instance.tr,
      'eu': instance.eu,
      'ht': instance.ht,
      'ka': instance.ka,
      'ur': instance.ur,
    };
